[package]
name = "svdp"
version = "0.1.0"
edition = "2024"
description = "Admin tools for the St Vincent de Paul society at Nativity Catholic Church in Menlo Park, CA."

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
