services:
  dev:
    build: .
    volumes:
      - .:/svdp
      - ~/.tmux.conf:/root/.tmux.conf:ro
      - ~/.claude.json:/root/.claude.json
      - ~/.claude:/root/.claude
    network_mode: host
    stdin_open: true
    tty: true
    command: bash
